version: "2"
run:
  timeout: 10m10s

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema).ForceNew|Set
        - fmt.*
        - io.Close
  exclusions:
    generated: lax
    paths:
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - examples$
